#!/bin/bash
# Setup script para c-fundamentals repo
# Crea estructura completa de directorios y archivos

set -e

echo "🚀 Setting up c-fundamentals repository..."

# Crear estructura de directorios
mkdir -p c-fundamentals/{src,tests,bin,docs}

# Crear subdirectorios por nivel
mkdir -p c-fundamentals/src/{01-basics,02-loops,03-arrays,04-strings,05-functions,06-pointers,07-structs}

# Crear CMakeLists.txt en lugar de Makefile
cat > c-fundamentals/CMakeLists.txt << 'EOF'
cmake_minimum_required(VERSION 3.15)
project(c_fundamentals C)

# Requerir C99 y opciones de compilación similares a las del Makefile original
set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
add_compile_options(-Wall -Wextra -Werror -pedantic -g)

# Buscar recursivamente todos los .c en src/
file(GLOB_RECURSE SRC_FILES CONFIGURE_DEPENDS ${CMAKE_SOURCE_DIR}/src/*.c)

# Para cada fuente, crear un ejecutable con nombre seguro basado en la ruta relativa
foreach(src IN LISTS SRC_FILES)
  file(RELATIVE_PATH rel ${CMAKE_SOURCE_DIR}/src ${src})
  # Reemplazar separadores por '_' y quitar la extensión
  string(REGEX REPLACE "[/\\\\]" "_" target_name ${rel})
  string(REGEX REPLACE "\\.c$" "" target_name ${target_name})
  # Reemplazar guiones por '_' para evitar posibles problemas en nombres de targets
  string(REGEX REPLACE "-" "_" target_name ${target_name})
  add_executable(${target_name} ${src})
  # Volcar binarios en el directorio bin/ del proyecto (no en build/)
  set_target_properties(${target_name} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
endforeach()

# Target de conveniencia para compilar todo rápidamente
add_custom_target(build_all DEPENDS ${PROJECT_NAME} ALL)
EOF

# Crear README.md (actualizado para CMake)
cat > c-fundamentals/README.md << 'EOF'
# C Fundamentals - 108 Exercises

Colección de ejercicios en C, organizados por niveles.

## Estructura

```
c-fundamentals/
├── src/
│   ├── 01-basics/      # Exercises 1-18
│   ├── 02-loops/       # Exercises 19-36
│   ├── 03-arrays/      # Exercises 37-56
│   ├── 04-strings/     # Exercises 57-72
│   ├── 05-functions/   # Exercises 73-86
│   ├── 06-pointers/    # Exercises 87-97
│   └── 07-structs/     # Exercises 98-108
├── bin/                # Binaries generated by CMake (RUNTIME_OUTPUT_DIRECTORY)
├── tests/              # Test files (opcional)
└── docs/               # Notas y documentación
```

## Construcción (CMake)

Se recomienda usar una carpeta `build/` fuera del árbol de fuentes para compilar.

```bash
# Desde la raíz del proyecto
mkdir -p build && cd build
cmake ../c-fundamentals
cmake --build . -- -j

# Los binarios se colocan en c-fundamentals/bin
ls ../c-fundamentals/bin
```

## Uso rápido

- Compilar todo: `cmake --build .`
- Ejecutable ejemplo (nombre generado según la ruta fuente):
  - `c-fundamentals/bin/01_basics_ex01` (ejemplo: el nombre usa `_` en vez de `/` y sin extensión)

## Progreso / Anotaciones

En vez de un archivo `EXERCISES.md`, se utiliza `PROGRESS.md` para llevar un registro de avances y notas.

---

Mantén el código en `src/` y usa `c-fundamentals/bin/` para ejecutar los ejercicios compilados.
EOF

# Crear .gitignore
cat > c-fundamentals/.gitignore << 'EOF'
# Compiled binaries
bin/
*.o
*.out
*.exe

# Debug files
*.dSYM/
*.gch
*.pch

# IDE files
.vscode/
.idea/
*.swp
*.swo
*~

# OS files
.DS_Store
Thumbs.db

# Test outputs
*.log
core
vgcore.*
EOF

# Crear template para ejercicios
cat > c-fundamentals/docs/TEMPLATE.c << 'EOF'
/**
 * Exercise XX: [Title]
 * 
 * Description:
 *   [What this exercise does]
 *
 * Input:
 *   [Expected input]
 *
 * Output:
 *   [Expected output]
 *
 * Example:
 *   Input:  [example input]
 *   Output: [example output]
 *
 * Difficulty: [Easy/Medium/Hard]
 * Time: [Estimated time to complete]
 */

#include <stdio.h>
#include <stdlib.h>

int main(void) {
    // Your code here
    
    return 0;
}
EOF

# Generar archivo de progreso/tracker (en lugar de EXERCISES.md)
cat > c-fundamentals/PROGRESS.md << 'EOF'
# Progress / Anotaciones

Este archivo sirve como tracker de progreso y lugar para notas rápidas.

Formato sugerido:

- Fecha - Nivel - ejercicio - estado - notas

Ejemplo:
- 2025-12-11 - 01-basics ex01 - hecho - Implementado "Hello World"
- 2025-12-12 - 02-loops ex19 - pendiente - revisar caso N=0

Puedes usar `docs/PROGRESS.md` para notas más largas por sesión o tema.

---

¡Buena práctica! Mantén actualizadas las entradas para seguir el progreso.
EOF

# Generate ALL 108 exercise templates with correct titles
echo "Generating 108 exercise templates..."

# Define all exercise titles
declare -a exercises=(
    # Level 1: Basics (1-18)
    "Hello World"
    "Variables básicas"
    "Suma de dos números"
    "Calculadora básica"
    "Celsius a Fahrenheit"
    "Área de círculo"
    "Intercambiar variables"
    "Mayor de 3"
    "Par o impar"
    "Año bisiesto"
    "Calificación con letras"
    "Calculadora con switch"
    "Días del mes"
    "Calculadora de IMC"
    "Descuento en tienda"
    "Suma de 1 a N"
    "Tabla de multiplicar"
    "Factorial"
    # Level 2: Loops (19-36)
    "Número primo"
    "Fibonacci hasta N"
    "Invertir número"
    "Palíndromo numérico"
    "Suma de dígitos"
    "Número Armstrong"
    "MCD (Máximo Común Divisor)"
    "MCM (Mínimo Común Múltiplo)"
    "Potencia"
    "Patrón de asteriscos"
    "Patrón numérico"
    "Números perfectos"
    "Adivina el número"
    "Tabla ASCII"
    "Binario a decimal"
    "Decimal a binario"
    "Serie matemática"
    "Contar vocales y consonantes"
    # Level 3: Arrays (37-56)
    "Suma de elementos"
    "Máximo y mínimo"
    "Promedio"
    "Invertir array"
    "Búsqueda lineal"
    "Búsqueda binaria"
    "Ordenamiento burbuja"
    "Ordenamiento por selección"
    "Ordenamiento por inserción"
    "Eliminar duplicados"
    "Rotación de array"
    "Fusionar arrays ordenados"
    "Segundo elemento más grande"
    "Frecuencia de elementos"
    "Separar pares e impares"
    "Transponer matriz"
    "Suma de matrices"
    "Multiplicación de matrices"
    "Matriz identidad"
    "Determinante 2x2"
    # Level 4: Strings (57-72)
    "Longitud de string (sin strlen)"
    "Copiar string (sin strcpy)"
    "Concatenar strings (sin strcat)"
    "Comparar strings (sin strcmp)"
    "Invertir string"
    "Palíndromo de string"
    "Contar palabras"
    "Mayúsculas/minúsculas"
    "Eliminar espacios"
    "Anagrama"
    "Primer carácter no repetido"
    "Comprimir string"
    "Validar email"
    "Cifrado César"
    "Subcadena sin repetir"
    "Tokenizar string"
    # Level 5: Functions (73-86)
    "Factorial recursivo"
    "Fibonacci recursivo"
    "Suma de dígitos recursivo"
    "Torre de Hanoi"
    "Potencia recursiva"
    "MCD recursivo"
    "Búsqueda binaria recursiva"
    "Invertir string recursivo"
    "Binario recursivo"
    "Suma de array recursivo"
    "Palíndromo recursivo"
    "Caminos en cuadrícula"
    "Permutaciones"
    "Subsecuencia creciente"
    # Level 6: Pointers (87-97)
    "Swap con punteros"
    "Suma con punteros"
    "Invertir con punteros"
    "String length con punteros"
    "Copiar string con punteros"
    "Array dinámico"
    "Redimensionar array"
    "Calculadora con callbacks"
    "Array de strings"
    "Matriz dinámica 2D"
    "Punteros a estructuras"
    # Level 7: Structs (98-108)
    "Estructura Punto"
    "Estructura Fecha"
    "Estructura Estudiante"
    "Lista de contactos"
    "Sistema de inventario"
    "Escribir/leer archivo texto"
    "Contar líneas/palabras"
    "Copiar archivo"
    "Agenda con archivo"
    "Sistema de estudiantes con archivo"
    "Estadísticas de archivo"
)

# Function to create exercise file
create_exercise() {
    local num=$1
    local title=$2
    local dir=$3
    local filename=$4

    # Asegurar que el directorio exista
    mkdir -p "$dir"

    cat > "$filename" << EOF
/**
 * Exercise ${num}: ${title}
 * 
 * Description:
 *   See EXERCISES.md for detailed description
 *
 * TODO: Implement this exercise
 */

#include <stdio.h>
#include <stdlib.h>

int main(void) {
    // Your code here
    
    return 0;
}
EOF
}

# Generate exercises for each level
idx=0

# Level 1: Basics (1-18)
for i in {01..18}; do
    num=$((10#$i))  # Remove leading zero for array index
    create_exercise "$i" "${exercises[$idx]}" "c-fundamentals/src/01-basics" "c-fundamentals/src/01-basics/ex${i}.c"
    ((idx++))
done

# Level 2: Loops (19-36)
for i in {19..36}; do
    create_exercise "$i" "${exercises[$idx]}" "c-fundamentals/src/02-loops" "c-fundamentals/src/02-loops/ex${i}.c"
    ((idx++))
done

# Level 3: Arrays (37-56)
for i in {37..56}; do
    create_exercise "$i" "${exercises[$idx]}" "c-fundamentals/src/03-arrays" "c-fundamentals/src/03-arrays/ex${i}.c"
    ((idx++))
done

# Level 4: Strings (57-72)
for i in {57..72}; do
    cat > "c-fundamentals/src/04-strings/ex${i}.c" << EOF
/**
 * Exercise ${i}: ${exercises[$idx]}
 * 
 * Description:
 *   See EXERCISES.md for detailed description
 *
 * TODO: Implement this exercise
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
    // Your code here
    
    return 0;
}
EOF
    ((idx++))
done

# Level 5: Functions (73-86)
for i in {73..86}; do
    create_exercise "$i" "${exercises[$idx]}" "c-fundamentals/src/05-functions" "c-fundamentals/src/05-functions/ex${i}.c"
    ((idx++))
done

# Level 6: Pointers (87-97)
for i in {87..97}; do
    create_exercise "$i" "${exercises[$idx]}" "c-fundamentals/src/06-pointers" "c-fundamentals/src/06-pointers/ex${i}.c"
    ((idx++))
done

# Level 7: Structs (98-108)
for i in {98..108}; do
    num=$(printf "%03d" $i)
    create_exercise "$num" "${exercises[$idx]}" "c-fundamentals/src/07-structs" "c-fundamentals/src/07-structs/ex${num}.c"
    ((idx++))
done

echo "✓ Created ALL 108 exercise templates with titles!"
echo "  01-basics:    18 files (ex01.c - ex18.c)"
echo "  02-loops:     18 files (ex19.c - ex36.c)"
echo "  03-arrays:    20 files (ex37.c - ex56.c)"
echo "  04-strings:   16 files (ex57.c - ex72.c)"
echo "  05-functions: 14 files (ex73.c - ex86.c)"
echo "  06-pointers:  11 files (ex87.c - ex97.c)"
echo "  07-structs:   11 files (ex098.c - ex108.c)"

# Crear script generador de ejercicios
cat > c-fundamentals/generate_exercise.sh << 'EOF'
#!/bin/bash
# Generate template for new exercise

if [ $# -ne 3 ]; then
    echo "Usage: $0 <level> <number> <title>"
    echo "Example: $0 01-basics 04 calculator"
    exit 1
fi

LEVEL=$1
NUM=$2
TITLE=$3

FILENAME="src/${LEVEL}/ex${NUM}_${TITLE}.c"

if [ -f "$FILENAME" ]; then
    echo "Error: File $FILENAME already exists"
    exit 1
fi

cat > "$FILENAME" << TEMPLATE
/**
 * Exercise ${NUM}: ${TITLE^}
 * 
 * Description:
 *   TODO: Add description
 *
 * Input:
 *   TODO: Describe input
 *
 * Output:
 *   TODO: Describe output
 */

#include <stdio.h>
#include <stdlib.h>

int main(void) {
    // TODO: Implement exercise
    
    return 0;
}
TEMPLATE

echo "✓ Created: $FILENAME"
echo "Edit the file and implement the exercise!"
EOF

chmod +x c-fundamentals/generate_exercise.sh

# Crear/actualizar docs/PROGRESS.md (detalle por sesiones)
cat > c-fundamentals/docs/PROGRESS.md << 'EOF'
# Progress Tracker

## Week 1

### Day 1 (Exercises 1-10)
- [ ] 01. Hello World
- [ ] 02. Variables básicas
- [ ] 03. Suma de dos números
- [ ] 04. Calculadora básica
- [ ] 05. Celsius a Fahrenheit
- [ ] 06. Área de círculo
- [ ] 07. Intercambiar variables
- [ ] 08. Mayor de 3
- [ ] 09. Par o impar
- [ ] 10. Año bisiesto

### Day 2 (Exercises 11-20)
...

## Notes

### Lessons Learned
- 

### Challenges Faced
- 

### Next Steps
- 
EOF

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. mkdir -p build && cd build"
echo "2. cmake ../c-fundamentals"
echo "3. cmake --build . -- -j   # compila todos los ejercicios"
echo "4. ls ../c-fundamentals/bin && ../c-fundamentals/bin/<nombre_del_ejecutable>"
echo ""
echo "Directory structure created in: ./c-fundamentals"
echo ""
echo "Happy coding! 🚀"
